# Spring properties
spring:
  application:
     name: heroes-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  datasource:
    initialize: true
  jpa:
    hibernate:
      ddl-auto: none  

                

# Map the error path to error template (for Thymeleaf)
error:
  path: /error

# HTTP Server
server:
  port: 2222
  display-name: Heroes
  statusPageUrlPath: /heroes

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:1111/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    

#  3. If using the Angel release-train ONLY, give the process a unique instance id 
#     so that multiple instances can register when running on SAME host.  This is
#     not needed since release-train Brixton.
#     NOTE-1: spring.application.instance_id is only set when run on Cloud Foundry,
#             so we fallback on the server-port when it is not defined
#     NOTE-2: Syntax ${x:${y}} = use $x if set, otherwise use $y
#   metadataMap:
#     instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
security:
  user:
    password:  password    

#---
#spring:
#  profiles: cloud
#eureka:
#  instance:
#    hostname: ${APPLICATION_DOMAIN}
#    nonSecurePort: 80

